### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by tudan188** [chorsley/useragent-picker-cli#23]
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='raw.githubusercontent.com', port=443): Max retries exceeded with url: /intoli/user-agents/master/src/user-agents.json.gz (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x00000184FDEA6CF8>: Failed to establish a new connection: [Errno 11004] getaddrinfo failed'))

**Comment by chorsley** [comment]
This looks like a temporary name resolution failure you had locally. I'm assuming it might run correctly now when you retry.
